from tkinter import *
from PIL import Image, ImageTk

root = Tk()
root.title("QUIZ APP")
root.geometry("400x700+1000+150")
root.resizable(False,False)
root.configure(bg="black")
Icon = Image.open("quizz.jpg")
icon = ImageTk.PhotoImage(Icon)
root.iconphoto(False,icon)
Img = Image.open("qiuz.gif")
image = ImageTk.PhotoImage(Img)
label = Label(root, image=image)
label.pack(pady=0)
score = 0

def correct():
    l.config(text=("Correct"))
    score = score + 1
    
def incorrect():
    l.config(text=("Incorrect"))
def end():
    q.config(text=("The End"),font=("arial", 25))
    l.config(text=("Thank you for trying out the quiz"))
    button1.pack_forget()
    button2.pack_forget()

def next():
    q.config(text=("How many bones are in the human body?"))
    l.config(text=(""))
    button1.config(text=("300"))
    button2.config(text=("206"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next1)
def next1():          
    q.config(text=("What is the hardest natural substance on Earth?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Rock"))
    button2.config(text=("Diamond"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next2)
def next2():          
    q.config(text=("The concept of gravity was discovered by which famous physicist?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Isaac Newton"))
    button2.config(text=("Galileo Galilei"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next3)
def next3():          
    q.config(text=("Which is the main gas that makes up the Earth's atmosphere?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Helium"))
    button2.config(text=("Nitrogen"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next4)
def next4():          
    q.config(text=("What does DNA stand for?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Deoxyribonucleic acid"))
    button2.config(text=("Dynogenicnucleic acid"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next5)
def next5():          
    q.config(text=("Humans and chimpanzees share roughly how much DNA?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("75 percent"))
    button2.config(text=("98 percent"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next6)
def next6():          
    q.config(text=("Roughly how long does it take for the sun's light to reach Earth?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("8 hours"))
    button2.config(text=("8 minutes"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next7)
def next7():          
    q.config(text=("Which famous British physicist wrote A Brief History of Time?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Stephen Hawking"))
    button2.config(text=("John C. Mallinson"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next8)
def next8():          
    q.config(text=("At what temperature are Celsius and Fahrenheit equal?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("-40"))
    button2.config(text=("-70"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next9)
def next9():          
    q.config(text=("What modern-day country was Marie Curie born in?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Scotland"))
    button2.config(text=("Poland"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next10)
def next10():          
    q.config(text=("What is the biggest planet in our solar system?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Jupiter"))
    button2.config(text=("Saturn"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next11)
def next11():          
    q.config(text=("What name is given for the number of protons found in the nucleus of an atom?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Atomic number"))
    button2.config(text=("Atomicity"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next12)
def next12():          
    q.config(text=("How many vertebrae does the average human possess?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("33"))
    button2.config(text=("47"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next13)
def next13():          
    q.config(text=("What was the name of the first man-made satellite launched by the Soviet Union in 1957?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Sirius"))
    button2.config(text=("Sputnik 1"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next14)
def next14():          
    q.config(text=("Which oath of ethics taken by doctors is named after an Ancient Greek physician?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Asclepius Oath"))
    button2.config(text=("Hippocratic Oath"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next15)
def next15():          
    q.config(text=("What is a material that will not carry an electrical charge called?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Insulator"))
    button2.config(text=("Disconductor"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next16)
def next16():          
    q.config(text=("Which Apollo moon mission was the first to carry a lunar rover?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Apollo 15"))
    button2.config(text=("Apollo 1M"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next17)
def next17():          
    q.config(text=("How many teeth does an adult human have?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("30"))
    button2.config(text=("32"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next18)
def next18():          
    q.config(text=("What is the study of mushrooms called?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Mycology"))
    button2.config(text=("Botany"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next19)
def next19():          
    q.config(text=("How many brains and how many hearts does an octopus have?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("9 brains, 3 hearts"))
    button2.config(text=("3 brains, 9 hearts"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next20)
def next20():          
    q.config(text=("What is the only letter not to appear on the periodic table?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Z"))
    button2.config(text=("J"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next21)
def next21():          
    q.config(text=("What is the fastest land animal in the world?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Deer"))
    button2.config(text=("Cheetah"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next22)
def next22():          
    q.config(text=("What is the only even prime number?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("2"))
    button2.config(text=("4"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next23)
def next23():          
    q.config(text=("What metal is the best conductor of electricity?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Silver"))
    button2.config(text=("Mecury"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next24)
def next24():          
    q.config(text=("What is the perimeter of a circle called?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("The circumference"))
    button2.config(text=("The intermediacy"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next25)
def next25():          
    q.config(text=("Sound travels faster in air than in water: true or false?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("True"))
    button2.config(text=("False"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next26)
def next26():          
    q.config(text=("Which of the world's oceans in the deepest?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("The Pacific"))
    button2.config(text=("The Atlantic"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next27)
def next27():          
    q.config(text=("What was the first vaccine to be developed against a contagious disease?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("The smallpox vaccine"))
    button2.config(text=("The Chickenpox vaccine"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next28)
def next28():          
    q.config(text=("Who is credited with the creation of the World Wide Web?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Alan Turing"))
    button2.config(text=("Tim Berners-Lee"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next29)
def next29():          
    q.config(text=("Lightning is hotter than the surface of the sun: true or false?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("True"))
    button2.config(text=("False"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next30)
def next30():          
    q.config(text=("Where in the human body can the smallest bone be found?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("The finger"))
    button2.config(text=("The ear"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next31)
def next31():          
    q.config(text=("How many bones do sharks have?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("0"))
    button2.config(text=("108"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next32)
def next32():          
    q.config(text=("What is sphenopalatine ganglioneuralgia the scientific term for?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Brain freeze"))
    button2.config(text=("Lung freeze"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next33)
def next33():          
    q.config(text=("What does USB stand for?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Unsectional Serial Bus"))
    button2.config(text=("Universal Serial Bus"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next34)
def next34():          
    q.config(text=("What is the largest desert on Earth?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Antartica"))
    button2.config(text=("Sahara"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next35)
def next35():          
    q.config(text=("In which year were the first collisions achieved in the Large Hadron Collider?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("2007"))
    button2.config(text=("2010"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next36)
def next36():          
    q.config(text=("What is the heaviest organ in the human body?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("The liver"))
    button2.config(text=("The lung"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next37)
def next37():          
    q.config(text=("What is the rarest blood type in humans?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("AC Negative"))
    button2.config(text=("AB Negative"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next38)
def next38():          
    q.config(text=("In which year was Pluto reclassified as a Dwarf Planet?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("2006"))
    button2.config(text=("2003"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next39)
def next39():          
    q.config(text=("What is the biggest animal in the world?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("The Antarctic blue whale"))
    button2.config(text=("The Pacific blue whale"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next40)
def next40():          
    q.config(text=("What is the only active volcano on mainland Europe called?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Mount Vesuvius"))
    button2.config(text=("Mount Etna"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next41)
def next41():          
    q.config(text=("What is desquamation the scientific term for?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Peeling skin"))
    button2.config(text=("Pulling hair"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next42)
def next42():          
    q.config(text=("How many days on Earth does it take for Venus to rotate once on its axis?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("413"))
    button2.config(text=("243"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next43)
def next43():          
    q.config(text=("How many states of matter are there?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("4"))
    button2.config(text=("3"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next44)
def next44():          
    q.config(text=("What does a Geiger Counter measure?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Radiation"))
    button2.config(text=("Pollusion"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next45)
def next45():          
    q.config(text=("What are natural satellites colloquially known as??"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("planetoid"))
    button2.config(text=("Moons"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next46)
def next46():          
    q.config(text=("In which year did the Apollo 13 space mission take place?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("1962"))
    button2.config(text=("1970"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=next47)
def next47():          
    q.config(text=("Electrons are smaller than atoms: true or false?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("True"))
    button2.config(text=("False"))
    button1.config(command=correct)
    button2.config(command=incorrect)
    button_next.config(command=next48)
def next48():          
    q.config(text=("How many teeth does an adult human have?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("30"))
    button2.config(text=("32"))
    button1.config(command=incorrect)
    button2.config(command=correct)
    button_next.config(command=end)
    button_next.config(text=("End"))

        
q = Label(root, text="What gas do living things need to survive ?", font=("arial", 15),bg="black" ,fg="white", wraplength=200)
q.pack(pady = 30)

l = Label(root, text="", font=("arial", 20, ), bg="black" ,fg="white")
l.pack(pady=25)

button1 = Button(root,text="Oxygen",font=("bold", 15, "bold"),bd=0,fg="black", command=correct)
button1.pack(pady=25)

button2 = Button(root,text="Hydrogen",font=("bold", 15, "bold"),bd=0,fg="black",command=incorrect)
button2.pack(pady=25)

button_next= Button(root,text="Next",font=("bold", 15, "bold"),bd=0,fg="black",command=next)
button_next.place(x=300, y=650)
root.mainloop()