from tkinter import *
from PIL import Image, ImageTk

root = Tk()
root.title("QUIZ APP")
root.geometry("400x700+1000+150")
root.resizable(False,False)
root.configure(bg="black")
Icon = Image.open("quizz.jpg")
icon = ImageTk.PhotoImage(Icon)
root.iconphoto(False,icon)
Img = Image.open("qiuz.gif")
image = ImageTk.PhotoImage(Img)
label = Label(root, image=image)
label.pack(pady=0)
score = 0

def correct():
    l.config(text=("Correct"))
    score = score + 1
    
def incorrect():
    l.config(text=("Incorrect"))
def next():
    q.config(text=("How many bones are in the human body?"))
    l.config(text=(""))
    button1.config(text=("300"))
    button2.config(text=("206"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next1)
def next1():          
    q.config(text=("What is the hardest natural substance on Earth?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Rock"))
    button2.config(text=("Diamond"))
    button2.config(command=incorrect)
    button1.config(command=correct)
    button_next.config(command=next2)
def next2():          
    q.config(text=("The concept of gravity was discovered by which famous physicist?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Isaac Newton"))
    button2.config(text=("Galileo Galilei"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next3)
def next3():          
    q.config(text=("Which is the main gas that makes up the Earth's atmosphere?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Helium"))
    button2.config(text=("Nitrogen"))
    button2.config(command=incorrect)
    button1.config(command=correct)
    button_next.config(command=next4)
def next4():          
    q.config(text=("What does DNA stand for?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Deoxyribonucleic acid"))
    button2.config(text=("Dynogenicnucleic acid"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next5)
def next5():          
    q.config(text=("Humans and chimpanzees share roughly how much DNA?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("75 percent"))
    button2.config(text=("98 percent"))
    button2.config(command=incorrect)
    button1.config(command=correct)
    button_next.config(command=next6)
def next6():          
    q.config(text=("Roughly how long does it take for the sun's light to reach Earth?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("8 hours"))
    button2.config(text=("8 minutes"))
    button2.config(command=incorrect)
    button1.config(command=correct)
    button_next.config(command=next7)
def next7():          
    q.config(text=("Which famous British physicist wrote A Brief History of Time?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Stephen Hawking"))
    button2.config(text=("John C. Mallinson"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next8)
def next8():          
    q.config(text=("At what temperature are Celsius and Fahrenheit equal?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("-40"))
    button2.config(text=("-70"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next9)
def next9():          
    q.config(text=("What modern-day country was Marie Curie born in?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Scotland"))
    button2.config(text=("Poland"))
    button2.config(command=incorrect)
    button1.config(command=correct)
    button_next.config(command=next10)
def next10():          
    q.config(text=("What is the biggest planet in our solar system?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Jupiter"))
    button2.config(text=("Saturn"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next11)
def next11():          
    q.config(text=("What name is given for the number of protons found in the nucleus of an atom?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Atomic number"))
    button2.config(text=("Atomicity"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next12)
def next12():          
    q.config(text=("How many vertebrae does the average human possess?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("33"))
    button2.config(text=("47"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next13)
def next13():          
    q.config(text=("What was the name of the first man-made satellite launched by the Soviet Union in 1957?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Sirius"))
    button2.config(text=("Sputnik 1"))
    button2.config(command=incorrect)
    button1.config(command=correct)
    button_next.config(command=next14)
def next14():          
    q.config(text=("Which oath of ethics taken by doctors is named after an Ancient Greek physician?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Asclepius Oath"))
    button2.config(text=("Hippocratic Oath"))
    button2.config(command=incorrect)
    button1.config(command=correct)
    button_next.config(command=next15)
def next15():          
    q.config(text=("What is a material that will not carry an electrical charge called?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Insulator"))
    button2.config(text=("Disconductor"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next16)
def next16():          
    q.config(text=("Which Apollo moon mission was the first to carry a lunar rover?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Rock"))
    button2.config(text=("Diamond"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next17)
def next17():          
    q.config(text=("How many teeth does an adult human have?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Rock"))
    button2.config(text=("Diamond"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next18)
def next18():          
    q.config(text=("What is the study of mushrooms called?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Rock"))
    button2.config(text=("Diamond"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next19)
def next19():          
    q.config(text=("How many brains and how many hearts does an octopus have?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Rock"))
    button2.config(text=("Diamond"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next20)
def next20():          
    q.config(text=("What is the only letter not to appear on the periodic table?"))
    q.config(font=("arial", 15))
    l.config(text=(""))
    button1.config(text=("Rock"))
    button2.config(text=("Diamond"))
    button2.config(command=correct)
    button1.config(command=incorrect)
    button_next.config(command=next1)
        
q = Label(root, text="What gas do living things need to survive ?", font=("arial", 15),bg="black" ,fg="white", wraplength=200)
q.pack(pady = 30)

l = Label(root, text="", font=("arial", 20, ), bg="black" ,fg="white")
l.pack(pady=25)

button1 = Button(root,text="Oxygen",font=("bold", 15, "bold"),bd=0,fg="black", command=correct)
button1.pack(pady=25)

button2 = Button(root,text="Hydrogen",font=("bold", 15, "bold"),bd=0,fg="black",command=incorrect)
button2.pack(pady=25)

button_next= Button(root,text="Next",font=("bold", 15, "bold"),bd=0,fg="black",command=next)
button_next.place(x=300, y=650)
root.mainloop()